Repository emmanuelbg-10/ConectaIA, pull requests merged in 2025-05, with the labels that each got.

#5 Implement Authentication layout
  .env.example
  app/Http/Controllers/Admin/AdminUserController.php
  app/Http/Controllers/PublicationController.php
  app/Http/Middleware/HandleInertiaRequests.php
  app/Models/Hashtag.php
  app/Models/Interaction.php
  app/Models/Mention.php
  app/Models/Message.php
  app/Models/Notification.php
  app/Models/Publication.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/Providers/RouteServiceProvider.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/permission.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2025_05_12_185656_create_hashtags_table.php
  database/migrations/2025_05_12_185656_create_publications_table.php
  database/migrations/2025_05_12_185657_create_hashtag_publications_table.php
  database/migrations/2025_05_12_185657_create_messages_table.php
  database/migrations/2025_05_12_185657_create_notifications_table.php
  database/migrations/2025_05_12_185658_create_followings_table.php
  database/migrations/2025_05_12_185658_create_mentions_table.php
  database/migrations/2025_05_12_185701_create_interactions_table.php
  database/migrations/2025_05_13_144744_create_permission_tables.php
  database/migrations/2025_05_13_144811_remove_role_id_from_users_table.php
  database/migrations/2025_05_13_153129_add_soft_deletes_to_users_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RolesAndPermissionsSeeder.php
  package-lock.json
  package.json
  resources/js/Components/EmptyState.jsx
  resources/js/Components/LogoutButton.jsx
  resources/js/Components/NavLink.jsx
  resources/js/Components/Pagination.jsx
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Layouts/GuestLayout.jsx
  resources/js/Pages/Admin/Users/index.jsx
  resources/js/Pages/Auth/Login.jsx
  resources/js/Pages/Auth/Register.jsx
  resources/js/Pages/Dashboard.jsx
  resources/js/Pages/Profile/Edit.jsx
  resources/js/Pages/Profile/Partials/DeleteUserForm.jsx
  resources/js/Pages/Profile/Partials/UpdatePasswordForm.jsx
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx
  resources/js/Pages/Publications/Create.jsx
  resources/js/Pages/Publications/Index.jsx
  resources/js/app.jsx
  routes/web.php
  vite.config.js
Labels: frontend

#64 Implementacion visual de mensajes privados y funcionalidades de publicaciones (me gustas, respuestas y compartidos) con moderación de IA
  .env.example
  app/Http/Controllers/LikeController.php
  app/Http/Controllers/ModerationController.php
  app/Http/Controllers/PublicationController.php
  app/Http/Controllers/ResponseController.php
  app/Models/Like.php
  app/Models/Publication.php
  app/Models/Response.php
  app/Models/User.php
  app/Policies/ResponsePolicy.php
  app/Providers/AuthServiceProvider.php
  composer.json
  composer.lock
  database/migrations/2025_05_16_000940_create_likes_table.php
  database/migrations/2025_05_16_003830_create_responses_table.php
  package-lock.json
  package.json
  resources/js/Components/ChatSidebar.jsx
  resources/js/Components/ChatWindow.jsx
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Pages/Publications/Index.jsx
  resources/js/Pages/Publications/Show.jsx
  resources/views/app.blade.php
  resources/views/moderate-test.blade.php
  routes/web.php
Labels: frontend, backend

#65 Implementacion de funcionalidad de chats privados y publicaciones con imagenes, ademas de mejorar el layout de respuestas
  .env.copy
  app/Events/MessageSent.php
  app/Http/Controllers/AlertController.php
  app/Http/Controllers/FollowController.php
  app/Http/Controllers/FriendshipController.php
  app/Http/Controllers/MessageController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/PublicationController.php
  app/Models/Following.php
  app/Models/Friendship.php
  app/Models/Hashtag.php
  composer.json
  composer.lock
  config/broadcasting.php
  config/cloudinary.php
  config/filesystems.php
  config/services.php
  database/migrations/2025_05_18_153509_create_friendships_table.php
  database/migrations/2025_05_18_165638_add_profile_photo_url_to_users_table.php
  package-lock.json
  package.json
  resources/js/Components/ChatSidebar.jsx
  resources/js/Components/ChatWindow.jsx
  resources/js/Components/FollowButton.jsx
  resources/js/Components/FriendButton.jsx
  resources/js/Components/LogoutButton.jsx
  resources/js/Components/ModalAlerts.jsx
  resources/js/Components/UserMenu.jsx
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Pages/Alert.js
  resources/js/Pages/Alerts.jsx
  resources/js/Pages/Auth/Login.jsx
  resources/js/Pages/Profile.jsx
  resources/js/Pages/Publications/Index.jsx
  resources/js/Pages/Publications/Show.jsx
  resources/js/Pages/Settings/DeleteUserForm.jsx
  resources/js/Pages/Settings/Edit.jsx
  resources/js/Pages/Settings/UpdatePasswordForm.jsx
  resources/js/Pages/Settings/UpdateProfileInformationForm.jsx
  resources/js/app.jsx
  resources/js/bootstrap.js
  resources/views/app.blade.php
  routes/channels.php
  routes/web.php
Labels: frontend, backend

#68 Mejora visual de publicaciones, funcionalidades de ver publicaciones, generales. siguiendo, hashtags, buscar a personas y publicaciones y poder ver en cualquier pagina el chat privado.
  app/Events/MessageSent.php
  app/Http/Controllers/Admin/AdminUserController.php
  app/Http/Controllers/FriendshipController.php
  app/Http/Controllers/MessageController.php
  app/Http/Controllers/ModerationController.php
  app/Http/Controllers/PublicationController.php
  app/Http/Controllers/SearchController.php
  app/Http/Middleware/HandleInertiaRequests.php
  app/Models/Publication.php
  app/Models/User.php
  database/migrations/2025_05_20_135220_add_deleted_at_to_publications_table.php
  package-lock.json
  package.json
  resources/js/Components/Background.jsx
  resources/js/Components/ChatSidebar.jsx
  resources/js/Components/ChatWindow.jsx
  resources/js/Components/Loader.jsx
  resources/js/Components/ModalAlerts.jsx
  resources/js/Components/ModalSearch.jsx
  resources/js/Components/PrimaryButton.jsx
  resources/js/Components/PublicationActions.jsx
  resources/js/Components/TextInput.jsx
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Layouts/GuestLayout.jsx
  resources/js/Pages/Auth/ConfirmPassword.jsx
  resources/js/Pages/Auth/ForgotPassword.jsx
  resources/js/Pages/Auth/Login.jsx
  resources/js/Pages/Auth/Register.jsx
  resources/js/Pages/Profile.jsx
  resources/js/Pages/Publications/Index.jsx
  resources/js/Pages/Publications/Show.jsx
  resources/js/Pages/Welcome.jsx
  resources/js/app.jsx
  routes/web.php
Labels: frontend, backend

#69 Emmanuel
  .env.copy
  app/Http/Controllers/MessageController.php
  database/migrations/2025_05_12_185657_create_messages_table.php
  public/audio/pop.mp3
  resources/css/app.css
  resources/js/Components/ActiveChats.jsx
  resources/js/Components/Background.jsx
  resources/js/Components/ChatSidebar.jsx
  resources/js/Components/ChatWindow.jsx
  resources/js/Components/DangerButton.jsx
  resources/js/Components/Dropdown.jsx
  resources/js/Components/FollowButton.jsx
  resources/js/Components/FriendButton.jsx
  resources/js/Components/InputError.jsx
  resources/js/Components/InputLabel.jsx
  resources/js/Components/Modal.jsx
  resources/js/Components/ModalSearch.jsx
  resources/js/Components/PublicationActions.jsx
  resources/js/Components/ResponsiveNavLink.jsx
  resources/js/Components/SecondaryButton.jsx
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Pages/Admin/Users/index.jsx
  resources/js/Pages/Auth/ConfirmPassword.jsx
  resources/js/Pages/Auth/ForgotPassword.jsx
  resources/js/Pages/Auth/Login.jsx
  resources/js/Pages/Auth/Register.jsx
  resources/js/Pages/Chats.jsx
  resources/js/Pages/Publications/Show.jsx
  resources/js/Pages/Welcome.jsx
  routes/web.php
  vite.config.js
Labels: frontend, backend

#70 feat: implementacion de imagenes en chat privado, eliminacion de dashboard, animacion en guestLayout e implementacion de hashtags
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Http/Controllers/Auth/ConfirmablePasswordController.php
  app/Http/Controllers/Auth/EmailVerificationNotificationController.php
  app/Http/Controllers/Auth/EmailVerificationPromptController.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Auth/VerifyEmailController.php
  app/Http/Controllers/SearchController.php
  resources/js/Components/ChatWindow.jsx
  resources/js/Components/ModalAlerts.jsx
  resources/js/Components/ModalImage.jsx
  resources/js/Components/ModalSearch.jsx
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Pages/Auth/Login.jsx
  resources/js/Pages/Chats.jsx
  resources/js/Pages/Dashboard.jsx
  resources/js/Pages/Publications/Index.jsx
  resources/js/Pages/Publications/Show.jsx
  routes/web.php
Labels: frontend, backend

#73 Implementacion de favicon, mejora de filtrado de hashtag y limpieza de formulario desde de crear publicacion
  public/favicon.ico
  resources/js/Layouts/AuthenticatedLayout.jsx
  resources/js/Pages/Publications/Create.jsx
  resources/js/Pages/Publications/Index.jsx
  resources/js/Pages/Publications/Show.jsx
  resources/views/app.blade.php
Labels: frontend

#72 Documentación del backend
  app/Http/Controllers/Admin/AdminUserController.php
  app/Http/Controllers/AlertController.php
  app/Http/Controllers/FollowController.php
  app/Http/Controllers/FriendshipController.php
  app/Http/Controllers/LikeController.php
  app/Http/Controllers/MessageController.php
  app/Http/Controllers/ModerationController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/PublicationController.php
  app/Http/Controllers/ResponseController.php
  app/Http/Controllers/SearchController.php
  app/Models/Following.php
  app/Models/Friendship.php
  app/Models/Hashtag.php
  app/Models/Interaction.php
  app/Models/Like.php
  app/Models/Mention.php
  app/Models/Message.php
  app/Models/Notification.php
  app/Models/Publication.php
  app/Models/Response.php
  app/Models/User.php
  app/Policies/ResponsePolicy.php
Labels: documentation, backend
